mongo:
  host: 192.168.0.102
  port: 27017
  username: name
  password: password
  userdb: admin

file:
  mongo:
    database: files
    collection: file
    geodatabase: geo
    textdatabase: text
  scanpath: E:\\code, F:\\code\java, D:\\
